title: "Cat.weekly"
url: "https://weekly.cat"
sass:
    sass_dir: _scss
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
